# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-20 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='httpdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=500, verbose_name='ip')),
                ('port', models.CharField(max_length=500, verbose_name='port')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('header', models.TextField(verbose_name='header')),
                ('appname', models.CharField(max_length=500, verbose_name='appname')),
                ('ipaddrs', models.CharField(max_length=500, verbose_name='ipaddrs')),
                ('domain', models.CharField(max_length=500, verbose_name='domain')),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tasksdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=500, verbose_name='任务状态')),
                ('taskname', models.CharField(max_length=500, verbose_name='任务名称')),
                ('taskdata', models.CharField(max_length=500, verbose_name='任务内容')),
                ('num', models.IntegerField(default=0, verbose_name='任务数量')),
                ('completenum', models.IntegerField(default=0, verbose_name='完成数量')),
                ('taskport', models.CharField(max_length=500, verbose_name='任务端口')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('cookie', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
