# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-20 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scantool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='httpdata',
        ),
    ]
